version: '3'
services:
  llmpedia:
    build: .
    env_file:
      - .env
    volumes:
      - ./imgs:/app/imgs
      - ./data:/app/data
      - ./data/arxiv_text:/app/data/arxiv_text
      - ./data/nonllm_arxiv_text:/app/data/nonllm_arxiv_text
    ports:
      - "8188:8188"  # ComfyUI interface
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome-stable
      - TZ=America/Los_Angeles