version: '3'
services:
  llmpedia:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./imgs:/app/imgs
      - .:/app/src
    ports:
      - "8188:8188"  # ComfyUI interface

  cronicle:
    image: soulteary/cronicle
    ports:
      - "3012:3012"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cronicle_data/data:/opt/cronicle/data:rw
      - ./cronicle_data/logs:/opt/cronicle/logs:rw
      - ./cronicle_data/plugins:/opt/cronicle/plugins:rw
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome-stable
      - TZ=America/Los_Angeles
      - CRONICLE_echo=1
      - CRONICLE_log_level=9
      - CRONICLE_server_comm_use_hostnames=1
      - CRONICLE_web_socket_use_hostnames=1
      - CRONICLE_base_app_url=http://159.89.81.16:3012
      - CRONICLE_web_socket_timeout=60000
      - CRONICLE_master_server=1
    hostname: cronicle