version: '3'
services:
  llmpedia:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./imgs:/app/imgs
      - .:/app/src

  cronicle:
    image: vimagick/cronicle
    ports:
      - "3012:3012"
    volumes:
      - ./cronicle_data:/opt/cronicle/data
    environment:
      - TZ=UTC